name: NPM INSTALL TEST

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  npmcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Try npm install (playwright only)
        run: |
          mkdir -p tmp-npm-test
          cd tmp-npm-test
          npm init -y
          npm install playwright --no-audit --no-fund --silent || true
          ls -la node_modules | sed -n '1,120p' || true
