name: NODE TEST

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  nodecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Node and NPM versions
        run: |
          node --version
          npm --version
      - name: Check scripts dir
        run: |
          if [ -d "./scripts" ]; then sd="scripts"; elif [ -d "./rss-feeds/scripts" ]; then sd="rss-feeds/scripts"; else sd=$(find . -type d -name scripts | head -n 1); sd="${sd#./}"; fi
          echo "SCRIPTS=$sd"
