name: TEST - Generate Feeds (smoke test)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo path
        run: |
          echo "Current working dir:"
          pwd
          echo "Root files:"
          ls -la

      - name: Simple echo test
        run: |
          echo "SMOKE TEST: workflow_dispatch works"
          date
          echo "List workflows dir:"
          ls -la .github/workflows || true
