name: Generate RSS feeds (stable + businesswire)

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

env:
  PYTHON_VERSION: '3.11'
  NODE_VERSION: '18'

permissions:
  contents: write

jobs:

  render-on-selfhosted:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect scripts dir
        id: detect
        shell: bash
        run: |
          if [ -d "./scripts" ]; then sd="scripts";
          elif [ -d "./rss-feeds/scripts" ]; then sd="rss-feeds/scripts";
          else sd=$(find . -type d -name scripts | head -n 1); sd="${sd#./}";
          fi
          echo "scripts_dir=$sd" >> $GITHUB_OUTPUT
          echo "Detected scripts_dir: $sd"

      - name: Set up Node.js (self-hosted)
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache scripts node_modules
        id: cache-node
        uses: actions/cache@v4
        with:
          path: |
            ${{ steps.detect.outputs.scripts_dir }}/node_modules
          key: node-mod-${{ runner.os }}-${{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-mod-${{ runner.os }}-${{ env.NODE_VERSION }}-

      - name: Install playwright into scripts (npm --prefix) and chromium (self-hosted, smart)
        shell: bash
        run: |
          SCRIPTS="${{ steps.detect.outputs.scripts_dir }}"
          if [ -z "$SCRIPTS" ]; then
            echo "No scripts dir detected -> skip playwright install"
            exit 0
          fi

          if [ ! -d "$SCRIPTS/node_modules/playwright" ]; then
            echo "Installing playwright package into $SCRIPTS (npm --prefix)..."
            npm install --prefix "$SCRIPTS" playwright --no-audit --no-fund --silent || { echo "npm install failed"; exit 1; }
          else
            echo "playwright package already present in $SCRIPTS/node_modules - skipping npm install"
          fi

          if [ -d "${HOME}/.cache/ms-playwright" ] && [ "$(ls -A ${HOME}/.cache/ms-playwright 2>/dev/null | wc -l)" -gt 0 ]; then
            echo "Playwright browsers already present in ${HOME}/.cache/ms-playwright -> skipping browser install"
          else
            echo "Playwright browsers not found in ${HOME}/.cache/ms-playwright -> installing chromium"
            npx --yes --prefix "$SCRIPTS" playwright install chromium || { echo "playwright browser install failed"; exit 1; }
          fi

          echo "Done playwright setup."

      - name: Render pages (parallel)
        shell: bash
        run: |
          SCRIPTS="${{ steps.detect.outputs.scripts_dir }}"
          if [ -z "$SCRIPTS" ]; then
            echo "No scripts dir detected -> skip rendering"
            exit 0
          fi
          mkdir -p "$SCRIPTS/rendered"
          if [ ! -f "$SCRIPTS/run_renders.js" ]; then
            echo "run_renders.js not found at $SCRIPTS/run_renders.js - skipping render"
            exit 0
          fi
          export RENDER_CONCURRENCY=${{ env.RENDER_CONCURRENCY || '4' }}
          node "$SCRIPTS/run_renders.js"
        env:
          SCRIPTS: ${{ steps.detect.outputs.scripts_dir }}
          RENDER_CONCURRENCY: 4

      - name: Upload rendered HTML as artifact
        uses: actions/upload-artifact@v4
        with:
          name: rendered-html
          path: ${{ steps.detect.outputs.scripts_dir }}/rendered

  build:
    needs: render-on-selfhosted
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download rendered HTML artifact
        uses: actions/download-artifact@v4
        with:
          name: rendered-html
          path: scripts/rendered

      - name: Show repo root (debug)
        run: |
          echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
          pwd
          ls -la
          echo "rendered dir (downloaded):"
          ls -la scripts/rendered || true

      - name: Detect scripts dir
        id: detect
        run: |
          if [ -d "./scripts" ]; then sd="scripts";
          elif [ -d "./rss-feeds/scripts" ]; then sd="rss-feeds/scripts";
          else sd=$(find . -type d -name scripts | head -n 1); sd="${sd#./}";
          fi
          echo "scripts_dir=$sd" >> $GITHUB_OUTPUT
          echo "Detected scripts_dir: $sd"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache scripts node_modules
        id: cache-node
        uses: actions/cache@v4
        with:
          path: |
            ${{ steps.detect.outputs.scripts_dir }}/node_modules
          key: node-mod-${{ runner.os }}-${{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-mod-${{ runner.os }}-${{ env.NODE_VERSION }}-

      - name: Install playwright into scripts (npm --prefix) and chromium (smart)
        shell: bash
        run: |
          SCRIPTS="${{ steps.detect.outputs.scripts_dir }}"
          if [ -z "$SCRIPTS" ]; then
            echo "No scripts dir detected -> skip playwright install"
            exit 0
          fi

          if [ ! -d "$SCRIPTS/node_modules/playwright" ]; then
            npm install --prefix "$SCRIPTS" playwright --no-audit --no-fund --silent || { echo "npm install failed"; exit 1; }
          fi

          if [ -d "${HOME}/.cache/ms-playwright" ] && [ "$(ls -A ${HOME}/.cache/ms-playwright 2>/dev/null | wc -l)" -gt 0 ]; then
            echo "Playwright browsers already present -> skipping"
          else
            npx --yes --prefix "$SCRIPTS" playwright install chromium || { echo "playwright browser install failed"; exit 1; }
          fi

      - name: Verify playwright is importable (sanity)
        if: steps.detect.outputs.scripts_dir != ''
        run: |
          SCRIPTS="${{ steps.detect.outputs.scripts_dir }}"
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          ls -la "$SCRIPTS/node_modules" | sed -n '1,200p' || true
          node -e "try { require('./${{ steps.detect.outputs.scripts_dir }}/node_modules/playwright'); console.log('playwright ok'); } catch(e) { console.error('playwright require failed:', e.message); process.exit(2); }"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          else
            pip install requests beautifulsoup4 feedgen lxml feedparser python-dateutil
          fi

      - name: Run feed generator (Python)
        run: |
          SCRIPTS="${{ steps.detect.outputs.scripts_dir }}"
          if [ -f "${SCRIPTS}/generate_feeds.py" ]; then
            python3 "${SCRIPTS}/generate_feeds.py"
          elif [ -f "scripts/generate_feeds.py" ]; then
            python3 scripts/generate_feeds.py
          else
            echo "generate_feeds.py not found -> abort"
            exit 1
          fi

      - name: Ensure output dir exists
        run: |
          mkdir -p feeds
          ls -la

      - name: Create timestamped zip of feeds
        id: create_zip
        run: |
          set -e
          ZIPNAME=feeds-${{ github.run_id }}-${{ github.run_number }}.zip
          if ls feeds/*.xml 1> /dev/null 2>&1; then
            zip -r "$ZIPNAME" feeds || true
          else
            mkdir -p feeds
            echo "no-feeds" > feeds/placeholder.txt
            zip -r "$ZIPNAME" feeds || true
          fi
          echo "zipname=$ZIPNAME" >> $GITHUB_OUTPUT
        shell: bash

      - name: Upload feeds artifact (zip)
        uses: actions/upload-artifact@v4
        with:
          name: feeds-${{ github.run_id }}-${{ github.run_number }}
          path: ${{ steps.create_zip.outputs.zipname }}
          if-no-files-found: warn

      - name: Merge feeds (generate dist/merged-feed.xml)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install feedparser feedgen python-dateutil
          fi
          python3 scripts/merge_feeds.py

      - name: Commit merged feed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add dist/merged-feed.xml || echo "no merged feed to add"
          git commit -m "Update merged feed" || echo "no changes to commit"
          git push

      - name: Show produced feeds
        run: |
          echo "Feeds dir listing:"
          ls -la feeds || true
          for f in feeds/*.xml; do
            echo "---- $f ----"
            head -n 40 "$f" || true
          done
