name: RENDER CALL TEST

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  rendercall:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Node version
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Run render_page.js against example.com
        run: |
          SCRIPTS="scripts"
          if [ ! -f "$SCRIPTS/render_page.js" ]; then echo "render_page.js not found at $SCRIPTS/render_page.js"; ls -la $SCRIPTS || true; exit 1; fi
          node "$SCRIPTS/render_page.js" https://example.com "$SCRIPTS/rendered/example.html" || true
          ls -la "$SCRIPTS/rendered" || true
