name: DETECT TEST

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  detect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Detect scripts dir and show sites.json
        run: |
          if [ -d "./scripts" ]; then sd="scripts"; elif [ -d "./rss-feeds/scripts" ]; then sd="rss-feeds/scripts"; else sd=$(find . -type d -name scripts | head -n 1); sd="${sd#./}"; fi
          echo "SCRIPTS=$sd"
          echo "PWD=$(pwd)"
          if [ -n "$sd" ] && [ -f "$sd/sites.json" ]; then
            echo "---- sites.json head ----"
            sed -n '1,80p' "$sd/sites.json"
            echo "---- end ----"
          else
            echo "sites.json not found at $sd/sites.json"
          fi
