name: Generate RSS feeds (Node renderer + Python)

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'   # opcional: roda a cada 2 horas

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Playwright (Node) and deps
        run: |
          # entra na pasta onde está o render_page.js / package.json se existir
          if [ -d "./scripts" ]; then
            cd ./scripts
            npm install playwright --no-audit --no-fund
            npx playwright install --with-deps
            cd ..
          else
            echo "Folder ./scripts not found - skipping Node install"
          fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          elif [ -f "rss-feeds/requirements.txt" ]; then
            pip install -r rss-feeds/requirements.txt
          else
            echo "No requirements.txt found - assuming minimal dependencies present"
          fi

      - name: Render pages that need JS (Node)
        run: |
          mkdir -p scripts/rendered

          echo "Rendering darkreading..."
          node scripts/render_page.js https://www.darkreading.com/ scripts/rendered/darkreading.html || echo "darkreading render failed"

          echo "Rendering iotworldtoday..."
          node scripts/render_page.js https://www.iotworldtoday.com/ scripts/rendered/iotworldtoday.html || echo "iotworldtoday render failed"

          echo "Rendered files listing:"
          ls -la scripts/rendered || true

      - name: Debug - show some files (optional)
        run: |
          echo "Listing scripts folder:"
          ls -la scripts || true
          echo "sites.json preview:"
          sed -n '1,200p' scripts/sites.json || true
          echo "rendered file heads (if any):"
          head -n 5 scripts/rendered/darkreading.html || true
          head -n 5 scripts/rendered/iotworldtoday.html || true

      - name: Run feed generator (Python)
        run: |
          python3 scripts/generate_feeds.py

      - name: Commit feeds
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add feeds/*.xml || true
          git commit -m "Update feeds" || echo "no changes to commit"
          git push origin HEAD:main || echo "push failed"
