name: Run feed generator (remote)

on:
  workflow_dispatch:

jobs:
  run-generator:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install requests beautifulsoup4 feedgen lxml python-dateutil
          fi

      - name: Ensure output dir exists
        run: |
          mkdir -p feeds
          ls -la

      - name: Run feed generator (Python)
        id: run_gen
        run: |
          set -o pipefail
          python3 scripts/generate_feeds.py 2>&1 | tee run_generate.log
          exit ${PIPESTATUS[0]}
        shell: bash

      - name: Debug listing (after generate)
        run: |
          echo "PWD: $(pwd)"
          ls -la
          ls -la feeds || true
          find . -maxdepth 3 -type f -name "*.xml" -print || true

      - name: Show produced feeds (sample & counts)
        if: always()
        run: |
          echo "=== Feeds dir listing (workspace) ==="
          ls -la feeds || true
          for f in feeds/*.xml; do
            echo "---- $f ----"
            head -n 40 "$f" || true
          done
          test -f run_generate.log && tail -n 200 run_generate.log || true
        shell: bash

      - name: Create zip of feeds (safe)
        run: |
          set -e
          ZIPNAME=feeds.zip
          # garante que a pasta existe
          mkdir -p feeds
          # se existirem .xml, adiciona; se não, cria placeholder para não falhar
          if ls feeds/*.xml 1> /dev/null 2>&1; then
            zip -r "$ZIPNAME" feeds || true
          else
            echo "No XML feeds found — creating placeholder" >&2
            echo "no-feeds" > feeds/placeholder.txt
            zip -r "$ZIPNAME" feeds || true
          fi
          ls -la "$ZIPNAME"

      - name: Upload feeds artifact (zip)
        uses: actions/upload-artifact@v4
        with:
          name: feeds-${{ github.run_id }}-${{ github.run_number }}
          path: feeds.zip
          if-no-files-found: warn
          retention-days: 7



      - name: Upload run log artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: run-generate-log-${{ github.run_id }}-${{ github.run_number }}
          path: run_generate.log
          retention-days: 7

      - name: Optional commit merged feed back to repo
        run: |
          if [ -f dist/merged-feed.xml ]; then
            git config user.name "github-actions[bot]"
            git config user.email "actions@github.com"
            git add dist/merged-feed.xml || true
            if git diff --cached --quiet; then
              echo "No changes to commit for dist/merged-feed.xml"
            else
              git commit -m "Update merged feed (auto)" || true
              git push || echo "git push failed (maybe token/permission?)"
            fi
          else
            echo "No dist/merged-feed.xml found -> skipping commit"
          fi
        shell: bash
